from django.urls import path
from .import views
from django.views.generic import *

urlpatterns = [
    # path("home/", views.accueil, name="home"),
    # path("home", TemplateViews.as_view(template_name="monApp/page_home.html")),
    path("home/", views.HomeView.as_view(), name="home"),
    # path("about/", views.about, name="about"),
    path("about/", views.AboutView.as_view(), name="about"),
    # path("contact/", views.contact, name="contact"),
    # path("contact/", views.ContactView.as_view(), name="contact"),
    path("contact/", views.ContactView, name="contact"),
    path("email-sent/", views.EmailSentView.as_view(), name="email-sent"),
    # path("home/<param>", views.accueil, name="accueil"),
    path("home/<param>", views.HomeView.as_view(), name="accueil"),
    # path("produits/", views.ListProduits, name="produits"),
    path("produits/", views.ProduitListView.as_view(), name="lst_prdts"),
    path("produit/<pk>/", views.ProduitDetailView.as_view(), name="dtl_prdt"),
    # path("produit/", views.ProduitCreate, name="crt-prdt"),
    path("produit/", views.ProduitCreateView.as_view(), name="crt-prdt"),
    path("produit/<pk>/change/", views.ProduitUpdateView.as_view(), name="prdt-chng"),
    path("produit/<pk>/delete/", views.ProduitDeleteView.as_view(), name="sup_prdt"),
    # path("categories/", views.ListCategorie, name="categories"),
    path("categorie/", views.CategorieCreateView.as_view(), name="crt-cat"),
    path("categories/", views.CategorieView.as_view(), name="lst_cats"),
    path("categorie/<pk>/", views.CategorieDetailView.as_view(), name="dtl_cat"),
    path("categorie/<pk>/change/", views.CategorieUpdateView.as_view(), name="cat-chng"),
    path("categorie/<pk>/delete/", views.CategorieDeleteView.as_view(), name="sup_cat"),
    # path("statuts/", views.ListStatuts, name="statuts"),
    path("statuts/", views.StatutView.as_view(), name="lst_sts"),
    path("statut/", views.StatutCreateView.as_view(), name="crt-sts"),
    path("statut/<pk>/change/", views.StatutUpdateView.as_view(), name="sts-chng"),
    path("statut/<pk>/delete/", views.StatutDeleteView.as_view(), name="sup_sts"),
    path("statut/<pk>/", views.StatutDetailView.as_view(), name="dtl_statut"),
    # path("rayons/", views.ListRayons, name="rayons"),
    path("rayons/", views.RayonsView.as_view(), name="lst_rayons"),
    path("rayon/<pk>/", views.RayonDetailView.as_view(), name="dtl_rayon"),
    path("rayon/", views.RayonCreateView.as_view(), name="crt-ray"),
    path("rayon/<pk>/change/", views.RayonUpdateView.as_view(), name="ray-chng"),
    path("rayon/<pk>/delete/", views.RayonDeleteView.as_view(), name="sup_ray"),
    path("rayon/<pk>/cntnr/", views.ContenirCreateView.as_view(), name='cntnr-crt'),
    path("rayon/<pk>/updt-cntnr/", views.ContenirUpdateView.as_view(), name='cntnr-updt'),
    path("rayon/<pk>/delete-cntnr/", views.ContenirDeleteView.as_view(), name='cntnr-sup'),
    # urls de connexion, inscription et déconnexion
    path('login/', views.ConnectView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.DisconnectView.as_view(), name='logout'),
    # path('view/', views.my_view, name="test"),
]