# Generated by Django 5.2.6 on 2025-09-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFab',
            field=models.DateField(auto_now=True),
        ),
    ]
