# Generated by Django 5.2.6 on 2025-09-09 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='dateFab',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
