# Generated by Django 5.2.6 on 2025-09-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_alter_produit_datefab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='id',
        ),
        migrations.AddField(
            model_name='contenir',
            name='pk',
            field=models.CompositePrimaryKey('refProd', 'idRayon', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
