# Generated by Django 5.2.6 on 2025-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0008_remove_contenir_id_contenir_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='pk',
        ),
        migrations.AddField(
            model_name='contenir',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='contenir',
            constraint=models.UniqueConstraint(fields=('refProd', 'idRayon'), name='contenir'),
        ),
    ]
