# Generated by Django 5.2.6 on 2025-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0009_remove_contenir_pk_contenir_id_contenir_contenir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='Qte',
            field=models.PositiveIntegerField(),
        ),
    ]
